//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Libro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Libro()
        {
            this.Prestamo_Libro = new HashSet<Prestamo_Libro>();
        }
    
        public int lib_id { get; set; }
        public string lib_nombre { get; set; }
        public Nullable<bool> lib_disponible { get; set; }
        public Nullable<int> cat_id { get; set; }
        public Nullable<int> edi_id { get; set; }
        public Nullable<int> aut_id { get; set; }
        [JsonIgnore]
        public virtual Autor Autor { get; set; }
        [JsonIgnore]
        public virtual Categoria Categoria { get; set; }
        [JsonIgnore]
        public virtual Editorial Editorial { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamo_Libro> Prestamo_Libro { get; set; }
    }
}
