//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamo_Libro
    {
        public int pre_id { get; set; }
        public Nullable<System.DateTime> pre_fecha_inicio { get; set; }
        public Nullable<System.DateTime> pre_fecha_final { get; set; }
        public Nullable<int> lib_id { get; set; }
        public Nullable<int> usu_cedula { get; set; }
    
        public virtual Libro Libro { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
